/* Generated By:JavaCC: Do not edit this line. Grammar3Constants.java */
package compilerDesign.hw3.grammar;

public interface Grammar3Constants {

  int EOF = 0;
  int Int = 5;
  int Char = 6;
  int CharLiteral = 7;
  int Digit = 8;
  int Op = 9;
  int Print = 10;
  int LParen = 11;
  int RParen = 12;
  int LBrace = 13;
  int RBrace = 14;
  int Quote = 15;
  int Equals = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"int\"",
    "\"char\"",
    "<CharLiteral>",
    "<Digit>",
    "<Op>",
    "\"P\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"=\"",
  };

}
